#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/home/krka/downloads/gwt-2.1.1/gwt-user.jar:/home/krka/downloads/gwt-2.1.1/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src se.krka.sthlmcommute.web.client.ClientConstants  ;

